name: uav_data_generation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - --extra-index-url https://download.blender.org/pypi/
      - -e .[dev]
