name: uav_data_generation
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.4
  - torchvision=0.19
  - pytorch-cuda=12.1
  - pip:
      - -r requirements.txt
