site_name: Documentation for UAV data generation
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.tabs
    # - navigation.sections
    - navigation.top
    - content.code.copy
    - navigation.footer
    - navigation.indexes

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      base_path: [".", ".."]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - README.md
  - Getting started:
    - getting-started/index.md
    - getting-started/installation.md
    - getting-started/downloads.md
    - getting-started/pre-processing.md
    - getting-started/uav-generation.md
    - getting-started/harmonization.md
    - getting-started/weather-stylization.md
    - getting-started/post-processing.md
  - Design:
    - design/dataset.md
  - Datasets:
    - datasets/weather-anti-uav.md
  - resources.md
