[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "uav_data_generation"
authors = [{ name = "Leaf Ying", email = "leaf.ying.cs11@nycu.edu.tw" }]
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"

# these will also be installed in blender env
dependencies = [
    "pillow < 11",
    "numpy < 3",
    "matplotlib < 4",
    "pycocotools",
    "rich",
    "scikit-learn < 2",
    "mpi4py < 5",
    "python-dotenv",
]

[project.optional-dependencies]
runtime = [
    "awscli",
    "boto3",
    "bpy ~= 3.5.0",
    # after 2.8.0, we need to upgrade blender from 3.5.1 to 4.2.1
    "blenderproc ~= 2.7.2",
    "nuscenes-devkit",
]
dev = [
    "uav_data_generation[runtime]",
    "fake-bpy-module-3.5",
    "boto3-stubs[boto3,s3]",
    "transformers < 5",
    "safetensors",
    "packaging",
    "torch ~= 2.4.1",
    "torchvision ~= 0.19.1",
    "opencv-python < 5",
    "diffusers[torch] < 5",
    "accelerate < 1",
    "controlnet-aux",
    "ipywidgets",
    "ipykernel",
    "invisible-watermark",
    "compel",
    "pandas",
    # "fastdup; sys_platform != 'win32'",
    "mkdocs",
    "mkdocs-material",
    "mkdocs-git-revision-date-localized-plugin",
    "mkdocs-git-authors-plugin",
    "mkdocs-glightbox",
]

[tool.hatch.build.targets.uav_data_generation]
only-include = ["uav_data_generation"]
