[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "uav_data_generation"
authors = [{ name = "Leaf Ying", email = "leaf.ying.cs11@nycu.edu.tw" }]
readme = "README.md"
requires-python = ">=3.10"
version = "0.0.1"

# these will be installed in blender env
dependencies = [
    "pillow",
    "numpy < 2.0.0",
    "matplotlib",
    "pycocotools",
    "rich",
    "scikit-learn < 2.0.0",
]

[project.optional-dependencies]
runtime = [
    "awscli",
    "bpy ~= 3.5.0",
    "fake-bpy-module-3.5",
    "blenderproc < 3.0.0",
    "torchmetrics[image] ~= 1.4.2",
]
dev = [
    "uav_data_generation[runtime]",
    "diffusers[torch] < 5.0.0",
    "transformers < 5.0.0",
    "accelerate < 1.0.0",
    "safetensors",
    "controlnet-aux",
    "ipywidgets",
    "ipykernel",
    "invisible-watermark",
    "opencv-python-headless < 5.0.0.0",
    "compel",
    "pandas",
    # "fastdup; sys_platform != 'win32'",
]

[project.scripts]
uav-gen-eval = "uav_data_generation.evaluation:cli"

[tool.hatch.build.targets.uav_data_generation]
only-include = ["uav_data_generation"]

[tool.ruff]
target-version = "py310"
